# version: "3.9"

services:
  app:
    build: .
    container_name: sirius-ai-agent
    ports:
      - "8000:8000"
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - DB_PATH=/data/chats.db
      - AFISHA_API_URL=http://pro.sirius-ft.ru/api/afisha/event/list
    volumes:
      - ./data:/data          # постоянное хранение БД
      - ./app/templates:/app/app/templates  # для hot-reload шаблонов (опционально)
    restart: unless-stopped